#=============================================#
#                 v.1.2.8                     #  
# █▀▀▀█ █  █ █  █ ▄▀▀▄ ▀█▀ █     █▀▄▀█ █▀▀▄   #
# ▀▀▀▄▄ █  █ █▀▀█ █▄▄█  █  █     █ █ █ █  █   #
# █▄▄▄█ ▀▄▄▀ █  █ █  █ ▄█▄ █▄▄█  █   █ █▄▄▀   #
#     𝗠𝗨𝗟𝗧𝗜𝗗𝗘𝗩𝗜𝗖𝗘 𝗪𝗛𝗔𝗧𝗦𝗔𝗣𝗣 𝗨𝗦𝗘𝗥 𝗕𝗢𝗧        #
#=============================================#
# 
#    * @project_name : YOUSAF BALOCH 
#    * @author : @yousafkhanbaloch
#    * @youtube : https://youtube.com/@Y.BGamer110?si=Gy91rOThNSeGfo3g
#    * @description : YOUSAF BALOCH,A Multi-functional Whatsapp bot.
#    * @version 1.2.8
# 
# Don't change this [ /SuhailTechInfo/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/YosafN/YOUSAF-BALOCH//root/yousaf
WORKDIR /root/yousafbaloch
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
